num=[1,2,3,4,5,6,7,8,9]
print(num)
print(type(num))
prog_lang=['hi','hello','my','name','is','chotu','how','can']
print(prog_lang)
print(type(prog_lang))
print("accessing the postive indexing")
print(prog_lang[0])
print(prog_lang[1])
print(prog_lang[2])
print(prog_lang[3])
print(prog_lang[4])
print(prog_lang[5])
print(prog_lang[6])
print(prog_lang[7])
print("-----------")
print("accessing the negative indexing")
print(prog_lang[-8])
print(prog_lang[-7])
print(prog_lang[-6])
print(prog_lang[-5])
print(prog_lang[-4])
print(prog_lang[-3])
print(prog_lang[-2])
print(prog_lang[-1])   