set={'black','red','yellow','green','orange'}
print(set)
print(type(set))
print("----------------------")
set.add("purple")
print(set)
set1={'lavender','indigo','rosegold','peach'}
set.update(set1)
print("-------------------------------------")
print(set)