num1=int(input("enter the first number:"))
num2=int(input("enter the second number:"))
print("addition:",(num1+num2))
print("subtraction:",(num1-num2))
print("multiplication:",(num1*num2))
print("division:",(num1/num2))
print("modula division:",(num1%num2))
print("exponent:",(num1**num2))
print("integer division:",(num1//num2))
print("floor division:",(-num1//num2))
