tuple=('python','c','c++','java','dart','flutter','go lang','react js','angular')
print(tuple)
print(type(tuple))
print("accessing the postive indexing")
print(tuple[0])
print(tuple[1])
print(tuple[2])
print(tuple[3])
print(tuple[4])
print(tuple[5])
print("-----------")
print(tuple[-6])
print(tuple[-5])
print(tuple[-4])
print(tuple[-3])
print(tuple[-2])
print(tuple[-1])   